@startuml 演習３－５
object "Aさん:利用者" as A{

}

object "Bさん:利用者" as B{

}

object "301号室:部屋" as h1{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}

object "302号室:部屋" as h2{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}

object "303号室:部屋" as h3{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}

A -- h1
B -- h3
@enduml