@startuml
left to right direction
[*] --> メニュー画面
メニュー画面 --> 予約と確認画面
予約と確認画面 --> メニュー画面
state c <<choice>>
予約と確認画面 --> c: 名前と電話番号入力
c -up-> あなたの順番画面: 登録ボタンを押した場合
c -right-> メニュー画面: 取り消しボタンを押した場合
c -right-> あなたの順番画面: 確認ボタンを押した場合
あなたの順番画面 --> メニュー画面
メニュー画面 --left--> [*]
@enduml