@startuml ユースケース図
actor 利用者 #DDDDDD;line:black;line.bold;
actor 従業員 #DDDDDD;line:black;line.bold;
actor 管理者 #DDDDDD;line:black;line.bold;
rectangle ホテル予約システム {
usecase 会員登録をする as K
usecase (<u>予約する</u>\n拡張点\nキャンペーン期間\n会員登録する) as Y
usecase キャンペーン as KP
usecase 空室状況を閲覧する as E
usecase 予約集計する as YS
usecase ログインする as L
usecase 空室状況を確認する as KJ
}
利用者 --> K
left to right direction
K ..> Y : <<extend>>
KP ..> Y : <<extend>>
Y ..> L : <<include>>
YS ..> L : <<include>>
利用者 --> E
従業員 <|-- 管理者
管理者 --> YS
従業員 --> KJ
KJ ..> L : <<include>>
left to right direction
@enduml