@startuml 演習３－３
class 利用者{
    -名前
    -住所
    -電話番号
}

class ホテル{
    -部屋
}

class 部屋{
    -タイプ
    -価格
    -キャンペーン価格
}

class 予約{
    -チェックイン日
    -滞在期間
    -値段
}

利用者 "*" -left- "1" ホテル
予約 "1"  -left- "1" 部屋
ホテル "1" o-- "*" 部屋
利用者 "1" -- "1" 予約
@enduml